[project]
name = "pysynphot"
version = "2.0.1"
dynamic = [
    "description", 
    "requires-python", 
    "license", 
    "authors", 
    "classifiers", 
    "dependencies"]

[build-system]
requires = [
    "setuptools>=30.3.0",
    "wheel",
    "numpy",
]
