name: CI

on:
  push:
  pull_request:
  schedule:
    # Weekly Wednesday 6AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 6 * * 3'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PYSYN_CDBS: "https://ssb.stsci.edu/trds"

jobs:
  initial_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install numpy astropy pytest-remotedata pytest-astropy-header
        python -m pip install .
    - name: Test without remote data
      run: pytest pysynphot

  coverage_dev_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install numpy pytest-remotedata pytest-astropy-header pytest-cov codecov requests
        python -m pip install --extra-index-url https://pypi.anaconda.org/astropy/simple astropy --pre --upgrade
        python -m pip install -e .
    # NOTE: If TRDS cannot take the hit, disable --remote-data
    - name: Test with coverage, dev astropy, and remote data
      run: pytest pysynphot --cov=./ --cov-report=xml --remote-data
    - name: Coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
